rearranged scripts

diff --git a/install_newsRoom b/install_newsRoom
--- a/install_newsRoom
+++ b/install_newsRoom
@@ -5,6 +5,11 @@ set -exuo pipefail
 export DEBIAN_FRONTEND=noninteractive
 export DBUS_SESSION_BUS_ADDRESS=/dev/null
 
+SUPERDESK_DIR=/opt/superdesk/server
+if [ ! -d "$SUPERDESK_DIR" ]; then
+echo "   ****Superdesk installations is missing!**** " 1>&2 ; exit 1;
+fi
+
 SuperdeskDomain=${1:-'localhost'}
 
 NewsRoomDomain=${2:-'localhost'}
@@ -22,60 +27,24 @@ _missing_db() {
 _skip_install() {
     dpkg -l | grep '^ii.*'$1 && [ -z ${pkg_upgrade:-''} ]
 }
-### databases
-# redis
-if ! _skip_install redis-server; then
-    apt-get -y install software-properties-common
-    add-apt-repository -y ppa:chris-lea/redis-server
-    apt-get -y update
-    apt-get -y install --no-install-recommends redis-server || (
-        # seems for some systems we must disable PrivateDevices,
-        # otherwise redis fails on starting
-        # https://bugs.launchpad.net/ubuntu/+source/redis/+bug/1663911
-        path=/etc/systemd/system/redis-server.service.d
-        mkdir $path
-        echo '[Service]' > $path/redis.override.conf
-        echo 'PrivateDevices=no' >> $path/redis.override.conf
-    )
 
-    systemctl enable redis-server
-    systemctl restart redis-server
+## virtualenv and activate script
+python3env=/opt/python3env
+if [ ! -d "$python3env" ]; then
+curl -o- https://raw.githubusercontent.com/BlackOrder/SuperdeskInstall/master/subScripts/install_nvm_python3env | bash
 fi
 
-# mongo
-if ! _skip_install mongodb-org-server; then
-    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
-    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.6.list
+NVM_DIR="$HOME/.nvm"
+. "$NVM_DIR/nvm.sh"
+. "$NVM_DIR/bash_completion"
+. ~/.profile
+. ~/.bashrc
 
-    apt-get -y update
-    apt-get -y install --no-install-recommends \
-        mongodb-org-server \
-        mongodb-org-shell \
-        mongodb-org-tools
-fi
+## database
+curl -o- https://raw.githubusercontent.com/BlackOrder/SuperdeskInstall/master/subScripts/install_database | bash
 
-# tune mongo
-cfg=/etc/mongod.conf
-[ -f "${cfg}.bak" ] || mv $cfg $cfg.bak
-cat <<EOF > $cfg
-storage:
-  dbPath: /var/lib/mongodb
-  journal:
-    enabled: true
-  engine: wiredTiger
-
-systemLog:
-  destination: file
-  logAppend: true
-  path: /var/log/mongodb/mongod.log
-
-net:
-  port: 27017
-  bindIp: 0.0.0.0
-EOF
-unset cfg
-systemctl enable mongod
-systemctl restart mongod
+## elasticsearch 2.4 && 5.6
+curl -o- https://raw.githubusercontent.com/BlackOrder/SuperdeskInstall/master/subScripts/install_elasticsearch | bash
 
 locale-gen en_US.UTF-8
 
@@ -96,48 +65,18 @@ cat <<"EOF" > /etc/logrotate.d/newsroom
 EOF
 logrotate /etc/logrotate.conf
 
-apt-get update
-apt-get -y install --no-install-recommends \
-git python3 python3-dev python3-venv \
-build-essential libffi-dev \
-libtiff5-dev libjpeg8-dev zlib1g-dev \
-libfreetype6-dev liblcms2-dev libwebp-dev \
-curl libfontconfig libssl-dev \
-libxml2-dev libxslt1-dev \
-libxmlsec1-dev
-
-# node & npm
-if ! _skip_install nodejs; then
-    curl -sL https://deb.nodesource.com/setup_7.x | bash -
-    apt-get install -y nodejs
-
-    npm install -g grunt-cli
-fi
-
-node --version
-npm --version
-grunt --version
-
-## virtualenv and activate script
-env=/opt/newsroom/env
-[ -d $env ] && rm -rf $env
-python3 -m venv $env
-unset env
-
 cat <<"EOF" > /opt/newsroom/activate.sh
-. /opt/newsroom/env/bin/activate
+. $python3env/bin/activate
 
 set -a
 LC_ALL=en_US.UTF-8
 
 # some settings required by client
 PATH=/opt/newsroom/client/node_modules/.bin/:$PATH
-SUPERDESK_URL='http://localhost/api'
-SUPERDESK_WS_URL='ws://localhost/ws'
+SUPERDESK_URL='http://$SuperdeskDomain/api'
+SUPERDESK_WS_URL='ws://$SuperdeskDomain/ws'
 set +a
 EOF
-
-sed -i "s/localhost/${SuperdeskDomain}/g" /opt/newsroom/activate.sh
 
 _activate
 pip install -U pip wheel
@@ -165,7 +104,7 @@ time npm run build
 
 
 cat <<"EOF" > /opt/newsroom/activate.sh
-. /opt/newsroom/env/bin/activate
+. $python3env/bin/activate
 
 set -a
 LC_ALL=en_US.UTF-8
@@ -194,15 +133,13 @@ env = os.environ.get
 DEBUG=False
 WEBPACK_ASSETS_URL="http://$NewsRoomDomain/assets/"
 
-MAIL_SERVER = env('MAIL_SERVER', 'localhost')
+MAIL_SERVER = env('MAIL_SERVER', '$NewsRoomDomain')
 MAIL_PORT = int(env('MAIL_PORT', 25))
 MAIL_USE_TLS = env('MAIL_USE_TLS', False)
 MAIL_USE_SSL = env('MAIL_USE_SSL', False)
 MAIL_USERNAME = env('MAIL_USERNAME', '')
 MAIL_PASSWORD = env('MAIL_PASSWORD', '')
 EOF
-
-sed -i "s/localhost/${NewsRoomDomain}/g" /opt/newsroom/settings.py
 
 # Use latest honcho with --no-colour option
 pip install -U honcho gunicorn
@@ -265,47 +202,6 @@ location /assets {
 }
 EOF
 
-cat <<"EOF" > $path/params.conf
-tcp_nopush on;
-tcp_nodelay on;
-output_buffers 1 256k;
-postpone_output 0;
-keepalive_requests 210;
-reset_timedout_connection on;
-ignore_invalid_headers  on;
-server_tokens off;
-client_max_body_size 1024m;
-recursive_error_pages   on;
-server_name_in_redirect off;
-
-gzip on;
-gzip_disable "msie6";
-gzip_vary on;
-gzip_proxied any;
-gzip_comp_level 1;
-gzip_buffers 16 8k;
-gzip_http_version 1.1;
-gzip_types text/plain text/css application/json application/x-javascript application/javascript text/xml application/xml application/xml+rss text/javascript;
-
-proxy_set_header Host $host;
-proxy_set_header X-Forwarded-For $remote_addr;
-proxy_set_header Accept-Encoding "";
-proxy_buffering on;
-proxy_ignore_client_abort off;
-proxy_intercept_errors on;
-proxy_next_upstream error timeout invalid_header;
-proxy_redirect off;
-proxy_buffer_size 32k;
-proxy_buffers 8 32k;
-proxy_busy_buffers_size 64k;
-proxy_temp_file_write_size 64k;
-client_body_buffer_size 128k;
-proxy_connect_timeout 1;
-proxy_send_timeout 300;
-proxy_read_timeout 300;
-proxy_cache_min_uses 1;
-proxy_temp_path /var/tmp;
-EOF
 unset path
 systemctl enable nginx
 systemctl restart nginx
@@ -390,7 +286,7 @@ Wants=network.target
 After=network.target
 
 [Service]
-ExecStart=/bin/sh -c '. /opt/newsroom/env/bin/activate && exec python3 $smtp_py localhost 25 $mails'
+ExecStart=/bin/sh -c '. $python3env/bin/activate && exec python3 $smtp_py $NewsRoomDomain 25 $mails'
 WorkingDirectory=/opt/newsroom
 Restart=always
 
