fix

diff --git a/liveBlog b/liveBlog
--- a/liveBlog
+++ b/liveBlog
@@ -5,11 +5,18 @@ set -exuo pipefail
 export DEBIAN_FRONTEND=noninteractive
 export DBUS_SESSION_BUS_ADDRESS=/dev/null
 
+SUPERDESK_DIR=/opt/superdesk/server
+if [ ! -d "$SUPERDESK_DIR" ]; then
+echo "   ****Superdesk installations is missing!**** " 1>&2 ; exit 1;
+fi
+
 SuperdeskDomain=${1:-'localhost'}
+
+LiveBlogDomain=${2:-'localhost'}
 
 _activate() {
     set +ux
-    . /opt/superdesk/activate.sh
+    . /opt/liveblog/activate.sh
     set -ux
 }
 
@@ -21,7 +28,6 @@ _skip_install() {
     dpkg -l | grep '^ii.*'$1 && [ -z ${pkg_upgrade:-''} ]
 }
 
-
 ## virtualenv and activate script
 python3env=/opt/python3env
 if [ ! -d "$python3env" ]; then
@@ -31,8 +37,6 @@ fi
 NVM_DIR="$HOME/.nvm"
 . "$NVM_DIR/nvm.sh"
 . "$NVM_DIR/bash_completion"
-. ~/.profile
-. ~/.bashrc
 
 ## database
 curl -o- https://raw.githubusercontent.com/BlackOrder/SuperdeskInstall/master/subScripts/install_database | bash
@@ -40,15 +44,16 @@ curl -o- https://raw.githubusercontent.com/BlackOrder/SuperdeskInstall/master/su
 ## elasticsearch 2.4 && 5.6
 curl -o- https://raw.githubusercontent.com/BlackOrder/SuperdeskInstall/master/subScripts/install_elasticsearch | bash
 
+
 ### build
 locale-gen en_US.UTF-8
 
-[ -d /var/log/superdesk ] || mkdir -p /var/log/superdesk
+[ -d /var/log/liveblog ] || mkdir -p /var/log/liveblog
 systemctl disable rsyslog
 systemctl stop rsyslog
 
-cat <<"EOF" > /etc/logrotate.d/superdesk
-/var/log/superdesk/*.log {
+cat <<"EOF" > /etc/logrotate.d/liveblog
+/var/log/liveblog/*.log {
     rotate 7
     daily
     missingok
@@ -60,14 +65,14 @@ cat <<"EOF" > /etc/logrotate.d/superdesk
 EOF
 logrotate /etc/logrotate.conf
 
-cat <<"EOF" > /opt/superdesk/activate.sh
+cat <<"EOF" > /opt/liveblog/activate.sh
 . $python3env/bin/activate
 
 set -a
 LC_ALL=en_US.UTF-8
 
 # some settings required by client
-PATH=/opt/superdesk/client/node_modules/.bin/:$PATH
+PATH=/opt/liveblog/client/node_modules/.bin/:$PATH
 SUPERDESK_URL='http://$SuperdeskDomain/api'
 SUPERDESK_WS_URL='ws://$SuperdeskDomain/ws'
 set +a
@@ -77,12 +82,12 @@ _activate
 pip install -U pip wheel
 
 ## prepare source code
-repo=${repo:-'/opt/superdesk'}
+repo=${repo:-'/opt/liveblog'}
 [ -d $repo ] || mkdir $repo
 cd $repo
 if [ ! -d $repo/.git ]; then
     git init
-    git remote add origin https://github.com/superdesk/superdesk.git
+    git remote add origin https://github.com/liveblog/liveblog.git
     repo_ref=${repo_ref:-'heads/master'}
     repo_sha=
     git fetch origin $repo_ref:
@@ -91,31 +96,37 @@ if [ ! -d $repo/.git ]; then
     unset repo repo_ref
 fi
 
-cd /opt/superdesk/server
+cd /opt/liveblog/server
 [ -f dev-requirements.txt ] && req=dev-requirements.txt || req=requirements.txt
 time pip install -U -r $req
 
-cd /opt/superdesk/client
+cd /opt/liveblog/client
+time npm install
 
-nvm use lts/* && time npm install
+# 3.0.9, 3.1.0 versions need bower
+cd /opt/liveblog/client
+if [ -f bower.json ]; then
+    npm i bower
+    time bower --allow-root install
+fi
 
 
 ### deploy
-cat <<"EOF" > /opt/superdesk/activate.sh
-# you could write variables to /opt/superdesk/env.sh
+cat <<"EOF" > /opt/liveblog/activate.sh
+# you could write variables to /opt/liveblog/env.sh
 . $python3env/bin/activate
 
 set -a
 LC_ALL=en_US.UTF-8
 PYTHONUNBUFFERED=1
-PATH=/opt/superdesk/client/node_modules/.bin/:$PATH
+PATH=/opt/liveblog/client/node_modules/.bin/:$PATH
 
-[ ! -f /opt/superdesk/env.sh ] || . /opt/superdesk/env.sh
+[ ! -f /opt/liveblog/env.sh ] || . /opt/liveblog/env.sh
 
 HOST=${HOST:-$SuperdeskDomain}
 HOST_SSL=${HOST_SSL:-}
 DB_HOST=${DB_HOST:-$SuperdeskDomain}
-DB_NAME=${DB_NAME:-'superdesk'}
+DB_NAME=${DB_NAME:-'liveblog'}
 
 [ -n "${HOST_SSL:-}" ] && SSL='s' || SSL=''
 # To work properly inside and outside container, must be
@@ -145,7 +156,7 @@ CELERYBEAT_SCHEDULE_FILENAME=${CELERYBEAT_SCHEDULE_FILENAME:-/tmp/celerybeatsche
 CELERY_BROKER_URL=${CELERY_BROKER_URL:-$REDIS_URL}
 
 if [ -n "$AMAZON_CONTAINER_NAME" ]; then
-    AMAZON_S3_SUBFOLDER=${AMAZON_S3_SUBFOLDER:-'superdesk'}
+    AMAZON_S3_SUBFOLDER=${AMAZON_S3_SUBFOLDER:-'liveblog'}
     MEDIA_PREFIX=${MEDIA_PREFIX:-"http$SSL://$HOST/api/upload-raw"}
 
     # TODO: remove after full adoption of MEDIA_PREFIX
@@ -159,6 +170,10 @@ if [ -n "${SUPERDESK_TESTING:-}" ]; then
     ELASTICSEARCH_BACKUPS_PATH=/var/tmp/elasticsearch
     LEGAL_ARCHIVE=True
 fi
+
+### Liveblog custom
+S3_THEMES_PREFIX=${S3_THEMES_PREFIX:-"/liveblog/"}
+EMBEDLY_KEY=${EMBEDLY_KEY:-}
 set +a
 EOF
 
@@ -168,61 +183,60 @@ _activate
 [ -z "${prepopulate-1}" ] || (
 ### prepopulate
 _activate
-cd /opt/superdesk/server
-
-_sample_data() {
-    sample_data=${sample_data:-}
-    [ -z "$sample_data" ] || sample_data='--sample-data'
-    (python manage.py app:initialize_data --help | grep -- --sample-data) && sample_data=$sample_data || sample_data=
-}
-
+cd /opt/liveblog/server
 if _missing_db; then
-    _sample_data
-    python manage.py app:initialize_data $sample_data
-    python manage.py users:create -u admin -p admin -e 'admin@example.com' --admin
+    python manage.py app:initialize_data
+
+    # for master it should be '--admin=true' for devel just '--admin'
+    python manage.py users:create --help | grep -- '-a ADMIN' && admin='--admin=true' || admin='--admin'
+    python manage.py users:create -u admin -p admin -e 'admin@example.com' $admin
+
 else
     python manage.py app:initialize_data
 fi
-unset sample_data
+
+# fix 'IndexMissingException[[lb-*] missing]' errors
+curl -s -XPUT $ELASTICSEARCH_URL/$ELASTICSEARCH_INDEX
+
+python manage.py register_local_themes
+python manage.py register_bloglist
 )
 
 [ -z "${grunt_build-1}" ] || (
-cd /opt/superdesk/client
-
-nvm use 7.10.1 && time grunt build --max-old-space-size=3000 --ws=ws://$SuperdeskDomain/ws
+cd /opt/liveblog/client
+time grunt build --max-old-space-size=3000 --ws=ws://$LiveBlogDomain/ws
 )
 
 # Use latest honcho with --no-colour option
 pip install -U honcho gunicorn
 
 gunicorn_opts='-t 300 -w 1 --access-logfile=- --access-logformat="%(m)s %(U)s status=%(s)s time=%(T)ss size=%(B)sb"'
-cat <<EOF > /opt/superdesk/server/Procfile
-logs: journalctl -u superdesk* -f >> /var/log/superdesk/main.log
+cat <<EOF > /opt/liveblog/server/Procfile
+logs: journalctl -u liveblog* -f >> /var/log/liveblog/main.log
 rest: gunicorn -b 0.0.0.0:5000 wsgi $gunicorn_opts
 wamp: python3 -u ws.py
 work: celery -A worker worker -c 1
 beat: celery -A worker beat --pid=
-capi: gunicorn -b 0.0.0.0:5400 content_api.wsgi $gunicorn_opts
 EOF
 
 
-cat <<"EOF" > /etc/systemd/system/superdesk.service
+cat <<"EOF" > /etc/systemd/system/liveblog.service
 [Unit]
-Description=superdesk
+Description=liveblog
 Wants=network.target
 After=network.target
 
 [Service]
-ExecStart=/bin/sh -c '. /opt/superdesk/activate.sh && exec honcho start --no-colour'
-WorkingDirectory=/opt/superdesk/server
+ExecStart=/bin/sh -c '. /opt/liveblog/activate.sh && exec honcho start --no-colour'
+WorkingDirectory=/opt/liveblog/server
 Restart=always
 RestartSec=10
 
 [Install]
 WantedBy=multi-user.target
 EOF
-systemctl enable superdesk
-systemctl restart superdesk
+systemctl enable liveblog
+systemctl restart liveblog
 
 # nginx
 if ! _skip_install nginx; then
@@ -235,15 +249,15 @@ if ! _skip_install nginx; then
 fi
 
 path=/etc/nginx/conf.d
-cat <<EOF > $path/superdesk.conf
+cat <<EOF > $path/liveblog.conf
 server {
     listen 80;
-    server_name $SuperdeskDomain;
-    include $path/superdesk.inc;
+    server_name $LiveBlogDomain;
+    include $path/liveblog.inc;
 }
 EOF
 
-cat <<EOF > $path/superdesk.inc
+cat <<EOF > $path/liveblog.inc
 location /ws {
     proxy_pass http://localhost:5100;
     proxy_http_version 1.1;
@@ -255,7 +269,7 @@ location /ws {
 
 location /api {
     proxy_pass http://localhost:5000;
-    proxy_set_header Host $HOST;
+    proxy_set_header Host $LiveBlogDomain;
     expires epoch;
 
     sub_filter_once off;
@@ -263,17 +277,12 @@ location /api {
     sub_filter 'http://localhost' 'http://\$host';
 }
 
-location /contentapi {
-    proxy_pass http://localhost:5400;
-    proxy_set_header Host $HOST;
-    expires epoch;
-}
 
 location /.well-known {
     root /var/tmp;
 }
 location / {
-    root /opt/superdesk/client/dist;
+    root /opt/liveblog/client/dist;
 
     # TODO: use "config.js:server" for user installations
     sub_filter_once off;
@@ -283,59 +292,13 @@ location / {
 }
 EOF
 
-sed -i "s/tcp_nopush on/#tcp_nopush on/g" /etc/nginx/nginx.conf
-sed -i "s/tcp_nodelay on/#tcp_nodelay on/g" /etc/nginx/nginx.conf
-sed -i "s/gzip on/#gzip on/g" /etc/nginx/nginx.conf
-sed -i "s/gzip_disable /#gzip_disable /g" /etc/nginx/nginx.conf
-
-cat <<"EOF" > $path/params.conf
-tcp_nopush on;
-tcp_nodelay on;
-output_buffers 1 256k;
-postpone_output 0;
-keepalive_requests 210;
-reset_timedout_connection on;
-ignore_invalid_headers  on;
-server_tokens off;
-client_max_body_size 1024m;
-recursive_error_pages   on;
-server_name_in_redirect off;
-
-gzip on;
-gzip_disable "msie6";
-gzip_vary on;
-gzip_proxied any;
-gzip_comp_level 1;
-gzip_buffers 16 8k;
-gzip_http_version 1.1;
-gzip_types text/plain text/css application/json application/x-javascript application/javascript text/xml application/xml application/xml+rss text/javascript;
-
-proxy_set_header Host \$host;
-proxy_set_header X-Forwarded-For \$remote_addr;
-proxy_set_header Accept-Encoding "";
-proxy_buffering on;
-proxy_ignore_client_abort off;
-proxy_intercept_errors on;
-proxy_next_upstream error timeout invalid_header;
-proxy_redirect off;
-proxy_buffer_size 32k;
-proxy_buffers 8 32k;
-proxy_busy_buffers_size 64k;
-proxy_temp_file_write_size 64k;
-client_body_buffer_size 128k;
-proxy_connect_timeout 1;
-proxy_send_timeout 300;
-proxy_read_timeout 300;
-proxy_cache_min_uses 1;
-proxy_temp_path /var/tmp;
-EOF
 unset path
 systemctl enable nginx
 systemctl restart nginx
 
 
 [ -z "${smtp-1}" ] || (
-mails=/var/log/superdesk/mail
+mails=/var/log/liveblog/mail
 mkdir -p $mails
 
 smtp_py=/var/tmp/smtp.py
@@ -355,6 +318,7 @@ logging.basicConfig(
     datefmt='[%Y-%m-%d %H:%M:%S %Z]',
     format='%(asctime)s %(message)s'
 )
+
 
 class Server(smtpd.SMTPServer, object):
     """Logging-enabled SMTPServer instance."""
@@ -395,7 +359,7 @@ if __name__ == '__main__':
         log.info('Cleaning up')
 EOF
 
-cat <<EOF >> /etc/nginx/conf.d/superdesk.inc
+cat <<EOF >> /etc/nginx/conf.d/liveblog.inc
 location /mail {
     alias $mails/;
     default_type text/plain;
@@ -404,16 +368,16 @@ location /mail {
 }
 EOF
 
-service=superdesk-smtp
+service=liveblog-smtp
 cat <<EOF > /etc/systemd/system/$service.service
 [Unit]
-Description=Dev SMTP server for superdesk, it doesn't send real emails
+Description=Dev SMTP server for liveblog, it doesn't send real emails
 Wants=network.target
 After=network.target
 
 [Service]
-ExecStart=/bin/sh -c '. $python3env/bin/activate && exec python3 $smtp_py $SuperdeskDomain 25 $mails'
-WorkingDirectory=/opt/superdesk
+ExecStart=/bin/sh -c '. $python3env/bin/activate && exec python3 $smtp_py $LiveBlogDomain 25 $mails'
+WorkingDirectory=/opt/liveblog
 Restart=always
 
 [Install]
