rollback to publisher version

diff --git a/newsRoom b/newsRoom
--- a/newsRoom
+++ b/newsRoom
@@ -5,11 +5,6 @@ set -exuo pipefail
 export DEBIAN_FRONTEND=noninteractive
 export DBUS_SESSION_BUS_ADDRESS=/dev/null
 
-SUPERDESK_DIR=/opt/superdesk/server
-if [ ! -d "$SUPERDESK_DIR" ]; then
-echo "   ****Superdesk installations is missing!**** " 1>&2 ; exit 1;
-fi
-
 SuperdeskDomain=${1:-'localhost'}
 
 NewsRoomDomain=${2:-'localhost'}
@@ -27,9 +22,61 @@ _missing_db() {
 _skip_install() {
     dpkg -l | grep '^ii.*'$1 && [ -z ${pkg_upgrade:-''} ]
 }
+### databases
+# redis
+if ! _skip_install redis-server; then
+    apt-get -y install software-properties-common
+    add-apt-repository -y ppa:chris-lea/redis-server
+    apt-get -y update
+    apt-get -y install --no-install-recommends redis-server || (
+        # seems for some systems we must disable PrivateDevices,
+        # otherwise redis fails on starting
+        # https://bugs.launchpad.net/ubuntu/+source/redis/+bug/1663911
+        path=/etc/systemd/system/redis-server.service.d
+        mkdir $path
+        echo '[Service]' > $path/redis.override.conf
+        echo 'PrivateDevices=no' >> $path/redis.override.conf
+    )
 
-## database
-curl -o- https://raw.githubusercontent.com/BlackOrder/SuperdeskInstall/master/subScripts/database | bash
+    systemctl enable redis-server
+    systemctl restart redis-server
+fi
+
+# mongo
+if ! _skip_install mongodb-org-server; then
+    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
+    echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" \
+        > /etc/apt/sources.list.d/mongodb-org-3.2.list
+
+    apt-get -y update
+    apt-get -y install --no-install-recommends \
+        mongodb-org-server \
+        mongodb-org-shell \
+        mongodb-org-tools
+fi
+
+# tune mongo
+cfg=/etc/mongod.conf
+[ -f "${cfg}.bak" ] || mv $cfg $cfg.bak
+cat <<EOF > $cfg
+storage:
+  dbPath: /var/lib/mongodb
+  journal:
+    enabled: true
+  engine: wiredTiger
+
+systemLog:
+  destination: file
+  logAppend: true
+  path: /var/log/mongodb/mongod.log
+
+net:
+  port: 27017
+  bindIp: 0.0.0.0
+EOF
+unset cfg
+systemctl enable mongod
+systemctl restart mongod
 
 
 # elasticsearch
@@ -43,10 +90,9 @@ wait_elastic() {
         sleep 5
     done
 }
-
 if ! _skip_install elasticsearch; then
     # for elasticsearch 2.4.x declare next
-    # elastic_version=2.x
+    # elastic_version=2.4
     version=${elastic_version:-1.7}
     curl -s https://packages.elastic.co/GPG-KEY-elasticsearch | apt-key add -
     echo "deb https://packages.elastic.co/elasticsearch/$version/debian stable main" \
@@ -84,6 +130,7 @@ curl -s -XPUT 'http://localhost:9200/_snapshot/backups' \
 unset cfg es_backups
 
 
+### build
 locale-gen en_US.UTF-8
 
 [ -d /var/log/newsroom ] || mkdir -p /var/log/newsroom
@@ -103,12 +150,41 @@ cat <<"EOF" > /etc/logrotate.d/newsroom
 EOF
 logrotate /etc/logrotate.conf
 
+apt-get update
+apt-get -y install --no-install-recommends \
+git python3 python3-dev python3-venv \
+build-essential libffi-dev \
+libtiff5-dev libjpeg8-dev zlib1g-dev \
+libfreetype6-dev liblcms2-dev libwebp-dev \
+curl libfontconfig libssl-dev \
+libxml2-dev libxslt1-dev \
+libxmlsec1-dev
+
+# node & npm
+if ! _skip_install nodejs; then
+    curl -sL https://deb.nodesource.com/setup_7.x | bash -
+    apt-get install -y nodejs
+
+    npm install -g grunt-cli
+fi
+
+node --version
+npm --version
+grunt --version
+
+## virtualenv and activate script
+env=/opt/newsroom/env
+[ -d $env ] && rm -rf $env
+python3 -m venv $env
+unset env
+
+
 f="/opt/newsroom/activate.sh"
 dir=$(dirname "$f")
 mkdir -p "$dir"
 
 cat <<EOF > /opt/newsroom/activate.sh
-. /opt/python3env/bin/activate
+. /opt/newsroom/env/bin/activate
 
 set -a
 LC_ALL=en_US.UTF-8
@@ -140,20 +216,11 @@ fi
 
 cd /opt/newsroom
 time pip install -r requirements.txt
-
-set +ux
-source ~/.nvm/nvm.sh;
-nvm use lts/*;
-
 time npm install
-
 time npm run build
 
-set -ux
-
-
 cat <<"EOF" > /opt/newsroom/activate.sh
-. /opt/python3env/bin/activate
+. /opt/newsroom/env/bin/activate
 
 set -a
 LC_ALL=en_US.UTF-8
@@ -193,7 +260,7 @@ EOF
 # Use latest honcho with --no-colour option
 pip install -U honcho gunicorn
 
-cat <<EOF > /opt/newsroom/Procfile
+cat <<"EOF" > /opt/newsroom/Procfile
 app: python app.py
 logs: journalctl -u newsroom* -f >> /var/log/newsroom/main.log
 EOF
@@ -236,7 +303,7 @@ server {
 }
 EOF
 
-cat <<EOF > $path/newsroom.inc
+cat <<"EOF" > $path/newsroom.inc
 location / {
     proxy_pass http://localhost:5000;
     expires epoch;
@@ -335,7 +402,7 @@ Wants=network.target
 After=network.target
 
 [Service]
-ExecStart=/bin/sh -c '. /opt/python3env/bin/activate && exec python3 $smtp_py $NewsRoomDomain 25 $mails'
+ExecStart=/bin/sh -c '. /opt/newsroom/env/bin/activate && exec python3 $smtp_py $NewsRoomDomain 25 $mails'
 WorkingDirectory=/opt/newsroom
 Restart=always
 
diff --git a/superdesk b/superdesk
--- a/superdesk
+++ b/superdesk
@@ -5,18 +5,11 @@ set -exuo pipefail
 export DEBIAN_FRONTEND=noninteractive
 export DBUS_SESSION_BUS_ADDRESS=/dev/null
 
-SUPERDESK_DIR=/opt/superdesk/server
-if [ ! -d "$SUPERDESK_DIR" ]; then
-echo "   ****Superdesk installations is missing!**** " 1>&2 ; exit 1;
-fi
-
 SuperdeskDomain=${1:-'localhost'}
-
-LiveBlogDomain=${2:-'localhost'}
 
 _activate() {
     set +ux
-    . /opt/liveblog/activate.sh
+    . /opt/superdesk/activate.sh
     set -ux
 }
 
@@ -27,9 +20,62 @@ _missing_db() {
 _skip_install() {
     dpkg -l | grep '^ii.*'$1 && [ -z ${pkg_upgrade:-''} ]
 }
+### databases
+# redis
+if ! _skip_install redis-server; then
+    apt-get -y install software-properties-common
+    add-apt-repository -y ppa:chris-lea/redis-server
+    apt-get -y update
+    apt-get -y install --no-install-recommends redis-server || (
+        # seems for some systems we must disable PrivateDevices,
+        # otherwise redis fails on starting
+        # https://bugs.launchpad.net/ubuntu/+source/redis/+bug/1663911
+        path=/etc/systemd/system/redis-server.service.d
+        mkdir $path
+        echo '[Service]' > $path/redis.override.conf
+        echo 'PrivateDevices=no' >> $path/redis.override.conf
+    )
 
-## database
-curl -o- https://raw.githubusercontent.com/BlackOrder/SuperdeskInstall/master/subScripts/database | bash
+    systemctl enable redis-server
+    systemctl restart redis-server
+fi
+
+# mongo
+if ! _skip_install mongodb-org-server; then
+    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
+    echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" \
+        > /etc/apt/sources.list.d/mongodb-org-3.2.list
+
+    apt-get -y update
+    apt-get -y install --no-install-recommends \
+        mongodb-org-server \
+        mongodb-org-shell \
+        mongodb-org-tools
+fi
+
+# tune mongo
+cfg=/etc/mongod.conf
+[ -f "${cfg}.bak" ] || mv $cfg $cfg.bak
+cat <<EOF > $cfg
+storage:
+  dbPath: /var/lib/mongodb
+  journal:
+    enabled: true
+  engine: wiredTiger
+
+systemLog:
+  destination: file
+  logAppend: true
+  path: /var/log/mongodb/mongod.log
+
+net:
+  port: 27017
+  bindIp: 0.0.0.0
+EOF
+unset cfg
+systemctl enable mongod
+systemctl restart mongod
+
 
 # elasticsearch
 wait_elastic() {
@@ -42,10 +88,9 @@ wait_elastic() {
         sleep 5
     done
 }
-
 if ! _skip_install elasticsearch; then
     # for elasticsearch 2.4.x declare next
-    # elastic_version=2.x
+    # elastic_version=2.4
     version=${elastic_version:-1.7}
     curl -s https://packages.elastic.co/GPG-KEY-elasticsearch | apt-key add -
     echo "deb https://packages.elastic.co/elasticsearch/$version/debian stable main" \
@@ -86,12 +131,12 @@ unset cfg es_backups
 ### build
 locale-gen en_US.UTF-8
 
-[ -d /var/log/liveblog ] || mkdir -p /var/log/liveblog
-systemctl disable rsyslog || true
-systemctl stop rsyslog || true
+[ -d /var/log/superdesk ] || mkdir -p /var/log/superdesk
+systemctl disable rsyslog
+systemctl stop rsyslog
 
-cat <<"EOF" > /etc/logrotate.d/liveblog
-/var/log/liveblog/*.log {
+cat <<"EOF" > /etc/logrotate.d/superdesk
+/var/log/superdesk/*.log {
     rotate 7
     daily
     missingok
@@ -103,20 +148,44 @@ cat <<"EOF" > /etc/logrotate.d/liveblog
 EOF
 logrotate /etc/logrotate.conf
 
-f="/opt/liveblog/activate.sh"
-dir=$(dirname "$f")
-mkdir -p "$dir"
+apt-get update
+apt-get -y install --no-install-recommends \
+git python3 python3-dev python3-venv \
+build-essential libffi-dev \
+libtiff5-dev libjpeg8-dev zlib1g-dev \
+libfreetype6-dev liblcms2-dev libwebp-dev \
+curl libfontconfig libssl-dev \
+libxml2-dev libxslt1-dev \
+libxmlsec1-dev
 
-cat <<EOF > /opt/liveblog/activate.sh
-. /opt/python3env/bin/activate
+# node & npm
+if ! _skip_install nodejs; then
+    curl -sL https://deb.nodesource.com/setup_7.x | bash -
+    apt-get install -y nodejs
+
+    npm install -g grunt-cli
+fi
+
+node --version
+npm --version
+grunt --version
+
+## virtualenv and activate script
+env=/opt/superdesk/env
+[ -d $env ] && rm -rf $env
+python3 -m venv $env
+unset env
+
+cat <<"EOF" > /opt/superdesk/activate.sh
+. /opt/superdesk/env/bin/activate
 
 set -a
 LC_ALL=en_US.UTF-8
 
 # some settings required by client
-PATH=/opt/liveblog/client/node_modules/.bin/:\$PATH
-SUPERDESK_URL='http://$SuperdeskDomain/api'
-SUPERDESK_WS_URL='ws://$SuperdeskDomain/ws'
+PATH=/opt/superdesk/client/node_modules/.bin/:$PATH
+SUPERDESK_URL='http://localhost/api'
+SUPERDESK_WS_URL='ws://localhost/ws'
 set +a
 EOF
 
@@ -124,13 +193,13 @@ _activate
 pip install -U pip wheel
 
 ## prepare source code
-repo=${repo:-'/opt/liveblog'}
+repo=${repo:-'/opt/superdesk'}
 [ -d $repo ] || mkdir $repo
 cd $repo
 if [ ! -d $repo/.git ]; then
     git init
-    git remote add origin https://github.com/liveblog/liveblog.git
-    repo_ref=${repo_ref:-'heads/master'}
+    git remote add origin https://github.com/superdesk/superdesk.git
+    repo_ref=${repo_ref:-'heads/publisher'}
     repo_sha=
     git fetch origin $repo_ref:
     git checkout ${repo_sha:-FETCH_HEAD}
@@ -138,54 +207,40 @@ if [ ! -d $repo/.git ]; then
     unset repo repo_ref
 fi
 
-cd /opt/liveblog/server
+cd /opt/superdesk/server
 [ -f dev-requirements.txt ] && req=dev-requirements.txt || req=requirements.txt
 time pip install -U -r $req
 
-cd /opt/liveblog/client
-
-set +ux
-source ~/.nvm/nvm.sh;
-nvm use lts/*;
-
+cd /opt/superdesk/client
 time npm install
 
-# 3.0.9, 3.1.0 versions need bower
-cd /opt/liveblog/client
-if [ -f bower.json ]; then
-    npm i bower
-    time bower --allow-root install
-fi
-
-set -ux
 
 ### deploy
-cat <<"EOF" > /opt/liveblog/activate.sh
-# you could write variables to /opt/liveblog/env.sh
-. /opt/python3env/bin/activate
+cat <<"EOF" > /opt/superdesk/activate.sh
+# you could write variables to /opt/superdesk/env.sh
+. /opt/superdesk/env/bin/activate
 
 set -a
 LC_ALL=en_US.UTF-8
 PYTHONUNBUFFERED=1
-PATH=/opt/liveblog/client/node_modules/.bin/:$PATH
+PATH=/opt/superdesk/client/node_modules/.bin/:$PATH
 
-[ ! -f /opt/liveblog/env.sh ] || . /opt/liveblog/env.sh
+[ ! -f /opt/superdesk/env.sh ] || . /opt/superdesk/env.sh
 
-SUPERDESKHOST=${SUPERDESKHOST:-'ReplaceSuperdeskDomain'}
-HOST=${HOST:-'ReplaceLiveBlogDomain'}
+HOST=${HOST:-'localhost'}
 HOST_SSL=${HOST_SSL:-}
 DB_HOST=${DB_HOST:-'localhost'}
-DB_NAME=${DB_NAME:-'liveblog'}
+DB_NAME=${DB_NAME:-'superdesk'}
 
 [ -n "${HOST_SSL:-}" ] && SSL='s' || SSL=''
 # To work properly inside and outside container, must be
 # - "proxy_set_header Host <host>;" in nginx
 # - the same "<host>" for next two settings
 # TODO: try to fix at backend side, it should accept any host
-SUPERDESK_URL="http$SSL://$SUPERDESKHOST/api"
-CONTENTAPI_URL="http$SSL://$SUPERDESKHOST/contentapi"
-SUPERDESK_WS_URL="ws$SSL://$SUPERDESKHOST/ws"
-SUPERDESK_CLIENT_URL="http$SSL://$SUPERDESKHOST"
+SUPERDESK_URL="http$SSL://$HOST/api"
+CONTENTAPI_URL="http$SSL://$HOST/contentapi"
+SUPERDESK_WS_URL="ws$SSL://$HOST/ws"
+SUPERDESK_CLIENT_URL="http$SSL://$HOST"
 
 MONGO_URI="mongodb://$DB_HOST/$DB_NAME"
 LEGAL_ARCHIVE_URI="mongodb://$DB_HOST/${DB_NAME}_la"
@@ -205,8 +260,8 @@ CELERYBEAT_SCHEDULE_FILENAME=${CELERYBEAT_SCHEDULE_FILENAME:-/tmp/celerybeatsche
 CELERY_BROKER_URL=${CELERY_BROKER_URL:-$REDIS_URL}
 
 if [ -n "$AMAZON_CONTAINER_NAME" ]; then
-    AMAZON_S3_SUBFOLDER=${AMAZON_S3_SUBFOLDER:-'liveblog'}
-    MEDIA_PREFIX=${MEDIA_PREFIX:-"http$SSL://$SUPERDESKHOST/api/upload-raw"}
+    AMAZON_S3_SUBFOLDER=${AMAZON_S3_SUBFOLDER:-'superdesk'}
+    MEDIA_PREFIX=${MEDIA_PREFIX:-"http$SSL://$HOST/api/upload-raw"}
 
     # TODO: remove after full adoption of MEDIA_PREFIX
     AMAZON_SERVE_DIRECT_LINKS=${AMAZON_SERVE_DIRECT_LINKS:-True}
@@ -219,15 +274,8 @@ if [ -n "${SUPERDESK_TESTING:-}" ]; then
     ELASTICSEARCH_BACKUPS_PATH=/var/tmp/elasticsearch
     LEGAL_ARCHIVE=True
 fi
-
-### Liveblog custom
-S3_THEMES_PREFIX=${S3_THEMES_PREFIX:-"/liveblog/"}
-EMBEDLY_KEY=${EMBEDLY_KEY:-}
 set +a
 EOF
-
-sed -i "s/ReplaceSuperdeskDomain/${SuperdeskDomain}/g" /opt/liveblog/activate.sh
-sed -i "s/ReplaceLiveBlogDomain/${LiveBlogDomain}/g" /opt/liveblog/activate.sh
 
 _activate
 
@@ -235,67 +283,61 @@ _activate
 [ -z "${prepopulate-1}" ] || (
 ### prepopulate
 _activate
-cd /opt/liveblog/server
+cd /opt/superdesk/server
+
+_sample_data() {
+    sample_data=${sample_data:-}
+    [ -z "$sample_data" ] || sample_data='--sample-data'
+    (python manage.py app:initialize_data --help | grep -- --sample-data) && sample_data=$sample_data || sample_data=
+}
+
 if _missing_db; then
-    python manage.py app:initialize_data
-
-    # for master it should be '--admin=true' for devel just '--admin'
-    python manage.py users:create --help | grep -- '-a ADMIN' && admin='--admin=true' || admin='--admin'
-    python manage.py users:create -u admin -p admin -e 'admin@example.com' $admin
-
+    _sample_data
+    python manage.py app:initialize_data $sample_data
+    python manage.py users:create -u admin -p admin -e 'admin@example.com' --admin
 else
     python manage.py app:initialize_data
 fi
-
-# fix 'IndexMissingException[[lb-*] missing]' errors
-curl -s -XPUT $ELASTICSEARCH_URL/$ELASTICSEARCH_INDEX
-
-python manage.py register_local_themes
-python manage.py register_bloglist
+unset sample_data
 )
 
 [ -z "${grunt_build-1}" ] || (
-cd /opt/liveblog/client
+cd /opt/superdesk/client
 
-set +ux
-source ~/.nvm/nvm.sh;
-nvm use 7.10.1;
-set -ux
-
-time sudo grunt build --max-old-space-size=3000 --ws=ws://$LiveBlogDomain/ws
+time grunt build --max-old-space-size=3000 --ws=ws://$SuperdeskDomain/ws
 )
 
 # Use latest honcho with --no-colour option
 pip install -U honcho gunicorn
 
 gunicorn_opts='-t 300 -w 1 --access-logfile=- --access-logformat="%(m)s %(U)s status=%(s)s time=%(T)ss size=%(B)sb"'
-cat <<EOF > /opt/liveblog/server/Procfile
-logs: journalctl -u liveblog* -f >> /var/log/liveblog/main.log
+cat <<EOF > /opt/superdesk/server/Procfile
+logs: journalctl -u superdesk* -f >> /var/log/superdesk/main.log
 rest: gunicorn -b 0.0.0.0:5000 wsgi $gunicorn_opts
 wamp: python3 -u ws.py
 work: celery -A worker worker -c 1
 beat: celery -A worker beat --pid=
+capi: gunicorn -b 0.0.0.0:5400 content_api.wsgi $gunicorn_opts
 EOF
 
 
-cat <<"EOF" > /etc/systemd/system/liveblog.service
+cat <<"EOF" > /etc/systemd/system/superdesk.service
 [Unit]
-Description=liveblog
+Description=superdesk
 Wants=network.target
 After=network.target
 
 [Service]
-ExecStart=/bin/sh -c '. /opt/liveblog/activate.sh && exec honcho start --no-colour'
-WorkingDirectory=/opt/liveblog/server
+ExecStart=/bin/sh -c '. /opt/superdesk/activate.sh && exec honcho start --no-colour'
+WorkingDirectory=/opt/superdesk/server
 Restart=always
 RestartSec=10
 
 [Install]
 WantedBy=multi-user.target
 EOF
-
-systemctl enable liveblog
-systemctl restart liveblog
+systemctl enable superdesk
+systemctl restart superdesk
 
 # nginx
 if ! _skip_install nginx; then
@@ -308,15 +350,14 @@ if ! _skip_install nginx; then
 fi
 
 path=/etc/nginx/conf.d
-cat <<EOF > $path/liveblog.conf
+cat <<EOF > $path/default.conf
 server {
-    listen 80;
-    server_name $LiveBlogDomain;
-    include $path/liveblog.inc;
+    listen 80 default;
+
+    include $path/*.inc;
 }
 EOF
-
-cat <<EOF > $path/liveblog.inc
+cat <<EOF > $path/default.inc
 location /ws {
     proxy_pass http://localhost:5100;
     proxy_http_version 1.1;
@@ -328,7 +369,7 @@ location /ws {
 
 location /api {
     proxy_pass http://localhost:5000;
-    proxy_set_header Host $LiveBlogDomain;
+    proxy_set_header Host $HOST;
     expires epoch;
 
     sub_filter_once off;
@@ -336,12 +377,17 @@ location /api {
     sub_filter 'http://localhost' 'http://\$host';
 }
 
+location /contentapi {
+    proxy_pass http://localhost:5400;
+    proxy_set_header Host $HOST;
+    expires epoch;
+}
 
 location /.well-known {
     root /var/tmp;
 }
 location / {
-    root /opt/liveblog/client/dist;
+    root /opt/superdesk/client/dist;
 
     # TODO: use "config.js:server" for user installations
     sub_filter_once off;
@@ -350,13 +396,54 @@ location / {
     sub_filter 'ws://localhost/ws' 'ws://\$host/ws';
 }
 EOF
+cat <<"EOF" > $path/params.conf
+tcp_nopush on;
+tcp_nodelay on;
+output_buffers 1 256k;
+postpone_output 0;
+keepalive_requests 210;
+reset_timedout_connection on;
+ignore_invalid_headers  on;
+server_tokens off;
+client_max_body_size 1024m;
+recursive_error_pages   on;
+server_name_in_redirect off;
 
+gzip on;
+gzip_disable "msie6";
+gzip_vary on;
+gzip_proxied any;
+gzip_comp_level 1;
+gzip_buffers 16 8k;
+gzip_http_version 1.1;
+gzip_types text/plain text/css application/json application/x-javascript application/javascript text/xml application/xml application/xml+rss text/javascript;
+
+proxy_set_header Host $host;
+proxy_set_header X-Forwarded-For $remote_addr;
+proxy_set_header Accept-Encoding "";
+proxy_buffering on;
+proxy_ignore_client_abort off;
+proxy_intercept_errors on;
+proxy_next_upstream error timeout invalid_header;
+proxy_redirect off;
+proxy_buffer_size 32k;
+proxy_buffers 8 32k;
+proxy_busy_buffers_size 64k;
+proxy_temp_file_write_size 64k;
+client_body_buffer_size 128k;
+proxy_connect_timeout 1;
+proxy_send_timeout 300;
+proxy_read_timeout 300;
+proxy_cache_min_uses 1;
+proxy_temp_path /var/tmp;
+EOF
 unset path
 systemctl enable nginx
 systemctl restart nginx
 
+
 [ -z "${smtp-1}" ] || (
-mails=/var/log/liveblog/mail
+mails=/var/log/superdesk/mail
 mkdir -p $mails
 
 smtp_py=/var/tmp/smtp.py
@@ -376,6 +463,7 @@ logging.basicConfig(
     datefmt='[%Y-%m-%d %H:%M:%S %Z]',
     format='%(asctime)s %(message)s'
 )
+
 
 class Server(smtpd.SMTPServer, object):
     """Logging-enabled SMTPServer instance."""
@@ -416,7 +504,7 @@ if __name__ == '__main__':
         log.info('Cleaning up')
 EOF
 
-cat <<EOF >> /etc/nginx/conf.d/liveblog.inc
+cat <<EOF >> /etc/nginx/conf.d/default.inc
 location /mail {
     alias $mails/;
     default_type text/plain;
@@ -425,16 +513,16 @@ location /mail {
 }
 EOF
 
-service=liveblog-smtp
+service=superdesk-smtp
 cat <<EOF > /etc/systemd/system/$service.service
 [Unit]
-Description=Dev SMTP server for liveblog, it doesn't send real emails
+Description=Dev SMTP server for superdesk, it doesn't send real emails
 Wants=network.target
 After=network.target
 
 [Service]
-ExecStart=/bin/sh -c '. /opt/python3env/bin/activate && exec python3 $smtp_py $LiveBlogDomain 25 $mails'
-WorkingDirectory=/opt/liveblog
+ExecStart=/bin/sh -c '. /opt/superdesk/env/bin/activate && exec python3 $smtp_py localhost 25 $mails'
+WorkingDirectory=/opt/superdesk
 Restart=always
 
 [Install]
